---
- name: Remove legal notice on start up message
  hosts: windows
  gather_facts: False

  tasks:
    - name: Remove Legal Notice Title
      win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticecaption
        state: absent
        delete_key: no

    - name: Remove Legal Notice Text
      win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticetext
        state: absent
        delete_key: no